### ISSUE TITLE
getting EOENT on project creation

### ISSUE THREAD

**Issue by amitport** [rocjs/roc#100]
running:

```
> roc new my-app web-app-react
```

produces:

```
Using v1.0.3 as template version

Installing template setup dependencies.
Error: spawn npm ENOENT
    at exports._errnoException (util.js:893:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by dlmr** [comment]
What operating system are you using? 

Looks like you might be on **Windows** and we are unfortunately not supporting it as of now.

**Comment by amitport** [comment]
yep...

**Comment by dlmr** [comment]
We are working on adding support for Windows but it's not our most prioritised issue currently unfortunately and it might take a little while before it's completed.

Follow along on the development of this through this issue #91, we will soon write down a detailed outline of what is missing for full Windows support.
