### ISSUE TITLE
roc dev segfaults on alpine-linux container on ubuntu host

### ISSUE THREAD

**Issue by fenchu** [rocjs/roc#181]
Hi 
When running "npm run dev" I get a segmentation fault. This may be in the lifecycle and how it shell executions inside the container. Running nodejs in alpine containers are very attractive due to small size.

```
bash-4.3# npm run dev --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev', '--verbose' ]
npm info using npm@3.10.10
npm info using node@v6.10.3
npm verb run-script [ 'predev', 'dev', 'postdev' ]
npm info lifecycle test1@1.0.0~predev: test1@1.0.0
npm info lifecycle test1@1.0.0~dev: test1@1.0.0

> test1@1.0.0 dev /src/react-app
> roc dev
Found a local version of Roc, will use that over the global one. 
Segmentation fault (core dumped)
```

```
bash-4.3# cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev', '--verbose' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle test1@1.0.0~predev: test1@1.0.0
6 silly lifecycle test1@1.0.0~predev: no script for predev, continuing
7 info lifecycle test1@1.0.0~dev: test1@1.0.0
8 verbose lifecycle test1@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle test1@1.0.0~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/src/react-app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle test1@1.0.0~dev: CWD: /src/react-app
11 silly lifecycle test1@1.0.0~dev: Args: [ '-c', 'roc dev' ]
12 silly lifecycle test1@1.0.0~dev: Returned: code: 139  signal: null
13 info lifecycle test1@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: test1@1.0.0 dev: `roc dev`
14 verbose stack Exit status 139
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid test1@1.0.0
16 verbose cwd /src/react-app
17 error Linux 4.4.0-75-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dev" "--verbose"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error test1@1.0.0 dev: `roc dev`
22 error Exit status 139
23 error Failed at the test1@1.0.0 dev script 'roc dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the test1 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     roc dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs test1
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls test1
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

```
bash-4.3# uname -a
Linux a47af19c1008 4.4.0-75-generic #96~14.04.1-Ubuntu SMP Thu Apr 20 11:06:30 UTC 2017 x86_64 Linux
bash-4.3# cat /etc/alpine-release 
3.6.0
bash-4.3# roc --version
Found a local version of Roc, will use that over the global one. 
1.0.0-rc.20

sh -c "roc dev" with the following env fails:
sh:sh,shFlag:-c, cmd:roc dev, conf:{"cwd":"/src/react-app","env":{"HOSTNAME":"a47af19c1008","TERM":"xterm","OLDPWD":"/src","PATH":"/usr/lib/node_modules/npm/bin/node-gyp-bin:/src/react-app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","PWD":"/src/react-app","VERSION":"v6.10.3","NPM_VERSION":"3","GIT_SSL_NO_VERIFY":"1","SHLVL":"1","HOME":"/root","_":"/usr/bin/npm","npm_package_name":"test1","npm_package_version":"1.0.0","npm_package_description":"test1","npm_package_author_name":"mobj","npm_package_license":"UNLICENSED","npm_package_private":"true","npm_package_scripts_build":"roc build","npm_package_scripts_dev":"roc dev","npm_package_scripts_start":"roc start","npm_package_dependencies_roc_package_web_app_react":"^1.0.0-beta.10","npm_package_devDependencies_roc_package_web_app_react_dev":"^1.0.0-beta.10","npm_package_devDependencies_roc_plugin_style_sass":"^1.0.0-beta.3","npm_config_loglevel":"verbose","npm_config_argv":"{\"remain\":[],\"cooked\":[\"run\",\"dev\",\"--loglevel\",\"verbose\"],\"original\":[\"run\",\"dev\",\"--verbose\"]}","npm_config_user_agent":"npm/3.10.10 node/v6.10.3 linux x64","npm_config_access":"","npm_config_always_auth":"","npm_config_also":"","npm_config_bin_links":"true","npm_config_browser":"","npm_config_ca":"","npm_config_cafile":"","npm_config_cache":"/root/.npm","npm_config_cache_lock_stale":"60000","npm_config_cache_lock_retries":"10","npm_config_cache_lock_wait":"10000","npm_config_cache_max":"Infinity","npm_config_cache_min":"10","npm_config_cert":"","npm_config_color":"true","npm_config_depth":"Infinity","npm_config_description":"true","npm_config_dev":"","npm_config_dry_run":"","npm_config_editor":"vi","npm_config_engine_strict":"","npm_config_force":"","npm_config_fetch_retries":"2","npm_config_fetch_retry_factor":"10","npm_config_fetch_retry_mintimeout":"10000","npm_config_fetch_retry_maxtimeout":"60000","npm_config_git":"git","npm_config_git_tag_version":"true","npm_config_global":"","npm_config_globalconfig":"/usr/etc/npmrc","npm_config_global_style":"","npm_config_group":"","npm_config_heading":"npm","npm_config_if_present":"","npm_config_ignore_scripts":"","npm_config_init_module":"/root/.npm-init.js","npm_config_init_author_name":"","npm_config_init_author_email":"","npm_config_init_author_url":"","npm_config_init_version":"1.0.0","npm_config_init_license":"ISC","npm_config_json":"","npm_config_key":"","npm_config_legacy_bundling":"","npm_config_link":"","npm_config_local_address":"","npm_config_long":"","npm_config_maxsockets":"50","npm_config_message":"%s","npm_config_node_version":"6.10.3","npm_config_npat":"","npm_config_onload_script":"","npm_config_only":"","npm_config_optional":"true","npm_config_parseable":"","npm_config_prefix":"/usr","npm_config_production":"","npm_config_progress":"true","npm_config_proprietary_attribs":"true","npm_config_proxy":"","npm_config_https_proxy":"","npm_config_rebuild_bundle":"true","npm_config_registry":"https://registry.npmjs.org/","npm_config_rollback":"true","npm_config_save":"","npm_config_save_bundle":"","npm_config_save_dev":"","npm_config_save_exact":"","npm_config_save_optional":"","npm_config_save_prefix":"^","npm_config_scope":"","npm_config_searchopts":"","npm_config_searchexclude":"","npm_config_searchsort":"name","npm_config_shell":"bash","npm_config_shrinkwrap":"true","npm_config_sign_git_tag":"","npm_config_strict_ssl":"true","npm_config_tag":"latest","npm_config_tag_version_prefix":"v","npm_config_tmp":"/tmp","npm_config_unicode":"","npm_config_unsafe_perm":"","npm_config_usage":"","npm_config_user":"","npm_config_userconfig":"/root/.npmrc","npm_config_umask":"0022","npm_config_version":"","npm_config_versions":"","npm_config_viewer":"man","npm_config_globalignorefile":"/usr/etc/npmignore","npm_lifecycle_event":"dev","NODE":"/usr/bin/node","npm_node_execpath":"/usr/bin/node","npm_execpath":"/usr/lib/node_modules/npm/bin/npm-cli.js","TMPDIR":"/src/react-app","npm_lifecycle_script":"roc dev"},"stdio":[0,1,2]}
```

The code that barks:
```
bash-4.3# cat /usr/lib/node_modules/npm/lib/utils/lifecycle.js | tail -n +234 | head -25
  var sh = 'sh'
  var shFlag = '-c'

  if (process.platform === 'win32') {
    sh = process.env.comspec || 'cmd'
    shFlag = '/d /s /c'
    conf.windowsVerbatimArguments = true
  }

  log.verbose('lifecycle', logid(pkg, stage), 'PATH:', env[PATH])
  log.verbose('lifecycle', logid(pkg, stage), 'CWD:', wd)
  log.silly('lifecycle', logid(pkg, stage), 'Args:', [shFlag, cmd])

  var proc = spawn(sh, [shFlag, cmd], conf)

  proc.on('error', procError)
  proc.on('close', function (code, signal) {
    log.silly('lifecycle', logid(pkg, stage), 'Returned: code:', code, ' signal:', signal)
    if (signal) {
      process.kill(process.pid, signal)
    } else if (code) {
      var er = new Error('Exit status ' + code)
    }
    procError(er) //<--------- This line, code is 139
  })
```

---
Regards MortenB

**Comment by andreasrs** [comment]
Hi 👋 

What does your Dockerfile look like? I will see if I can reproduce and help out.

**Comment by andreasrs** [comment]
@fenchu did you solve this?
