### ISSUE TITLE
Unable to build clean project

### ISSUE THREAD

**Issue by MartinTonne** [rocjs/roc#199]
Hi,
I've been at this all day, and would like some help.

My last try was using:
OS: Ubuntu 16.04 server
npm version: 3.5.2
node version: 4.2.6
roc version: 1-0-0-rc.23

I just followed the standard create new project guide(roc new myproject web-app-react etc), but when I try to run it(dev or build) I get the following error message:
```
/home/ubuntu/dasproject/node_modules/roc-package-web-app-react/lib/roc/index.js:45
    description: ({ context: { usedExtensions } }) => {
                  ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/dasproject/node_modules/roc-package-web-app-react/lib/index.js:8:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

I've tried on 4 virtual machines(3 Ubuntu, 1 Windows) and two non virtual(windows), same error.

Anyone else have this problem?
Or did I miss something with this new extensions stuff?

Thanks

**Comment by dlmr** [comment]
Hi!

The latest version requires Node 6, can you try upgrading to at least that version?

**Comment by MartinTonne** [comment]
Yep, that was the problem.
Might want to update the readme. :)

Note to self, installing npm does not include a up-to-date Node..

Thanks for the quick response! 👍

**Comment by dlmr** [comment]
Thanks for the note about the readme, sorry about that... 🙂
